name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y gdal-bin libgdal-dev
      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Lint & format
        run: |
          pip install black isort
          black --check .
          isort --check-only .
      - name: Smoke build artifacts (skip if raw missing)
        run: |
          if [ -f data/raw/gtfs_train.zip ] && [ -f data/raw/rent_gemeinde.csv ]; then
            python scripts/make_artifacts.py
          else
            echo "Raw data missing; skipping artifact build."
          fi
