name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps (GDAL)
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Lint & format (Python files only)
        run: |
          pip install black isort
          # Run black only on source, scripts, and app dirs
          black --check app/ scripts/ src/ setup.py
          # Run isort on the same
          isort --check-only app/ scripts/ src/ setup.py --profile black --line-length 100

      # Optional: quick artifact build if raw inputs are present in CI
      - name: Smoke build artifacts (skip if raw missing)
        run: |
          if [ -f data/raw/gtfs_train.zip ] && [ -f data/raw/rent_gemeinde.csv ]; then
            python scripts/make_artifacts.py
          else
            echo "Raw data missing; skipping artifact build."
          fi
